# Generated by Django 4.0.5 on 2022-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="symptom",
            name="name",
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
