# Generated by Django 4.0.5 on 2022-07-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_symptom_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['-date']},
        ),
    ]
